### ISSUE TITLE
Simplify with Run statement

### ISSUE THREAD

**Issue by zuphilip** [jneubert/gnd-wd-link#1]
I think you can simplify the script with something like:

```ahk
; hotkey ctrl-shift-h 
^+h::
  Send, ^c
  Run, "https://tools.wmflabs.org/wikidata-todo/resolver.php?lang=de&prop=P227&value=%Clipboard%"
  Return
```

**Comment by jneubert** [comment]
Hi Philip, I had problems with "Run", and found [the suggested solution](https://autohotkey.com/boards/viewtopic.php?t=41873) worked - though the problem probably is different, because I'm not on Windows 10. But thanks for your hint, and for applying the idea in other workflows! Cheers, Joachim
